"""Abstract runtime adapter contract."""

from typing import Any, Protocol


class RuntimeAdapter(Protocol):
    def runtime_info(self) -> dict[str, Any]: ...
    def load_model(self, model_id: str) -> Any: ...
    def model_fingerprint(self) -> dict[str, Any]: ...
    def prefill(self, text: str) -> Any: ...
    def capture_state(self) -> Any: ...
    def restore_state(self, state: Any) -> None: ...
    def generate_next(self, **kwargs: Any) -> Any: ...
